# 数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photography?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  # thymeleaf 模板
  thymeleaf:
    # 前缀名
    prefix: classpath:/templates/
    # 后缀名
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    # 开发阶段务必关闭缓存 (=false)
    cache: false

#指定端口号
server:
  port: 8089

#别名扫描
mybatis:
  type-aliases-package: com.tl.photo.domain


#配置外部访问文件（把上传的图片文件放到fileUpload文件夹下）   服务器地址：/mydata/fileUpload
cbs:
  imagesPath: file:/Users/tl/fileUpload/photos
#  imagesPath: file:/mydata/fileUpload
